//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestCrud3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Visitas
    {
        public int IdVisitas { get; set; }
        public System.DateTime Fecha { get; set; }
        public System.TimeSpan Hora_Entrada { get; set; }
        public System.TimeSpan Hora_Salida { get; set; }
        public int IdPersona { get; set; }
        public string Motivo_Visita { get; set; }
        public int IdArea { get; set; }
    
        public virtual Area Area { get; set; }
        public virtual Persona Persona { get; set; }
    }
}
